### ISSUE TITLE
Config section is not executed

### ISSUE THREAD

**Issue by dvzubarev** [benneti/spacemacs-jupyter#9]
Hi,
I noticed that `:config` section of use-package is not executed. Can you confirm that?
I fixed this by changing 
`(use-package jupyter` to `(use-package jupyter-repl`.
Since `jupyter` is kind of meta-package and never was loaded. 
 
I use spacemacs develop, emacs 26.3

**Comment by benneti** [comment]
Hi, sorry for the late reply.
That is indeed very good to know, I'll try to figure out a way to make it work. Maybe it should be an :init block instead, would you try this out?

**Comment by benneti** [comment]
it should work now, if not feel free to reopen the issue
